import {
  ArrowDownLeft,
  ArrowUpRight,
  Bot,
  Check,
  ChevronDown,
  Clock3,
  CreditCard,
  ExternalLink,
  Filter,
  MoreHorizontal,
  Search,
  ShieldCheck,
  Sparkles,
  WalletCards,
  XCircle,
} from "lucide-react";
import "../styles/Transactions.css";

const transactions = [
  {
    customer: "Rahul Sharma",
    initials: "RS",
    product: "Velocity Running Shoes + Socks",
    amount: "₹1,498",
    orderId: "order_Rz8K29x",
    paymentId: "pay_N7k29Lm",
    time: "2 min ago",
    status: "Paid",
    method: "UPI",
    agent: true,
  },
  {
    customer: "Ananya Verma",
    initials: "AV",
    product: "Aero Sports Jacket",
    amount: "₹1,899",
    orderId: "order_Rz7H82p",
    paymentId: "pay_N7f82Ax",
    time: "18 min ago",
    status: "Paid",
    method: "Card",
    agent: true,
  },
  {
    customer: "Arjun Mehta",
    initials: "AM",
    product: "Velocity Running Shoes",
    amount: "₹1,299",
    orderId: "order_Rz6P11q",
    paymentId: "—",
    time: "31 min ago",
    status: "Pending",
    method: "UPI",
    agent: true,
  },
  {
    customer: "Priya Kapoor",
    initials: "PK",
    product: "FlexRun Sports Shorts",
    amount: "₹899",
    orderId: "order_Rz5M73d",
    paymentId: "pay_N5m73Pd",
    time: "1 hr ago",
    status: "Paid",
    method: "Netbanking",
    agent: false,
  },
  {
    customer: "Vikram Singh",
    initials: "VS",
    product: "HydroMax Sports Bottle",
    amount: "₹349",
    orderId: "order_Rz4B92k",
    paymentId: "—",
    time: "2 hrs ago",
    status: "Failed",
    method: "Card",
    agent: false,
  },
];

function Transactions() {
  return (
    <div className="transactions-page">
      {/* HEADER */}

      <div className="transactions-header">
        <div>
          <div className="eyebrow">PAYMENTS & ORDERS</div>

          <h1>Transactions</h1>

          <p>
            Monitor orders, payments and revenue generated by your AI agent.
          </p>
        </div>

        <button className="export-button">
          Export
          <ArrowDownLeft size={14} />
        </button>
      </div>

      {/* METRICS */}

      <div className="transaction-stats">
        <TransactionMetric
          icon={<WalletCards size={18} />}
          title="Total Processed"
          value="₹1,84,200"
          change="+18.4%"
          positive
        />

        <TransactionMetric
          icon={<Check size={18} />}
          title="Successful Payments"
          value="142"
          change="+12.8%"
          positive
        />

        <TransactionMetric
          icon={<Bot size={18} />}
          title="Agent Attributed"
          value="₹42,600"
          change="+31.6%"
          positive
        />

        <TransactionMetric
          icon={<XCircle size={18} />}
          title="Failed Payments"
          value="6"
          change="-18.2%"
          positive
        />
      </div>

      {/* PAYMENT HEALTH */}

      <div className="payment-health">
        <div className="health-left">
          <div className="health-icon">
            <ShieldCheck size={20} />
          </div>

          <div>
            <span>PAYMENT INFRASTRUCTURE</span>
            <strong>Razorpay Test Mode</strong>
            <p>
              Payment processing and webhook delivery are operational.
            </p>
          </div>
        </div>

        <div className="health-status">
          <span />
          Operational
        </div>

        <div className="webhook-status">
          <div>
            <span>Webhook events</span>
            <strong>1,284</strong>
          </div>

          <div>
            <span>Success rate</span>
            <strong>99.8%</strong>
          </div>
        </div>
      </div>

      {/* TOOLBAR */}

      <div className="transactions-toolbar">
        <div className="transaction-search">
          <Search size={15} />
          <input placeholder="Search customer, order or payment ID..." />
        </div>

        <button className="transaction-filter">
          <Filter size={13} />
          All Status
          <ChevronDown size={12} />
        </button>

        <button className="transaction-filter">
          All Methods
          <ChevronDown size={12} />
        </button>

        <button className="transaction-filter">
          Last 30 days
          <ChevronDown size={12} />
        </button>
      </div>

      {/* TABLE */}

      <div className="transactions-table">
        <div className="transaction-table-head">
          <span>CUSTOMER</span>
          <span>ORDER</span>
          <span>AMOUNT</span>
          <span>PAYMENT</span>
          <span>STATUS</span>
          <span>AGENT</span>
          <span />
        </div>

        {transactions.map((transaction) => (
          <TransactionRow
            key={transaction.orderId}
            transaction={transaction}
          />
        ))}
      </div>

      {/* BOTTOM */}

      <div className="transaction-bottom">
        {/* LIVE EVENTS */}

        <div className="transaction-panel">
          <div className="transaction-panel-header">
            <div>
              <span>LIVE PAYMENT EVENTS</span>
              <strong>Webhook activity</strong>
            </div>

            <span className="live-indicator">
              <span />
              LIVE
            </span>
          </div>

          <WebhookEvent
            type="payment.captured"
            order="order_Rz8K29x"
            time="2 min ago"
            success
          />

          <WebhookEvent
            type="order.paid"
            order="order_Rz7H82p"
            time="18 min ago"
            success
          />

          <WebhookEvent
            type="payment.authorized"
            order="order_Rz6P11q"
            time="31 min ago"
          />

          <WebhookEvent
            type="payment.failed"
            order="order_Rz4B92k"
            time="2 hrs ago"
            failed
          />
        </div>

        {/* AGENT REVENUE */}

        <div className="transaction-panel agent-revenue-panel">
          <div className="transaction-panel-header">
            <div>
              <span>AGENT COMMERCE</span>
              <strong>Revenue attribution</strong>
            </div>

            <Bot size={17} />
          </div>

          <div className="agent-revenue-value">
            <strong>₹42,600</strong>

            <span>
              <ArrowUpRight size={13} />
              31.6%
            </span>
          </div>

          <p className="agent-revenue-description">
            Revenue generated through AI recommendations, cross-sells and
            personalized offers.
          </p>

          <div className="revenue-breakdown">
            <RevenueSource
              label="Cross-sells"
              value="₹18,400"
              percent="43%"
            />

            <RevenueSource
              label="Personalized offers"
              value="₹14,200"
              percent="33%"
            />

            <RevenueSource
              label="Upsells"
              value="₹10,000"
              percent="24%"
            />
          </div>

          <button className="view-audit">
            <Sparkles size={13} />
            View Agent Audit Trail
            <ArrowUpRight size={13} />
          </button>
        </div>
      </div>
    </div>
  );
}

function TransactionMetric({
  icon,
  title,
  value,
  change,
  positive,
}: {
  icon: React.ReactNode;
  title: string;
  value: string;
  change: string;
  positive: boolean;
}) {
  return (
    <div className="transaction-stat">
      <div className="transaction-stat-top">
        <span>{title}</span>

        <div>{icon}</div>
      </div>

      <strong>{value}</strong>

      <span className={positive ? "stat-positive" : "stat-negative"}>
        {positive ? <ArrowUpRight size={12} /> : <ArrowDownLeft size={12} />}
        {change}
        <small>vs last month</small>
      </span>
    </div>
  );
}

function TransactionRow({
  transaction,
}: {
  transaction: (typeof transactions)[number];
}) {
  const statusClass =
    transaction.status === "Paid"
      ? "transaction-paid"
      : transaction.status === "Pending"
      ? "transaction-pending"
      : "transaction-failed";

  return (
    <div className="transaction-row">
      <div className="transaction-customer">
        <div className="transaction-avatar">
          {transaction.initials}
        </div>

        <div>
          <strong>{transaction.customer}</strong>

          <span>{transaction.product}</span>
        </div>
      </div>

      <div className="order-info">
        <strong>{transaction.orderId}</strong>
        <span>{transaction.time}</span>
      </div>

      <strong className="transaction-amount">
        {transaction.amount}
      </strong>

      <div className="payment-info">
        <strong>{transaction.method}</strong>
        <span>{transaction.paymentId}</span>
      </div>

      <span className={`transaction-status ${statusClass}`}>
        {transaction.status === "Paid" && <Check size={10} />}
        {transaction.status === "Pending" && <Clock3 size={10} />}
        {transaction.status === "Failed" && <XCircle size={10} />}
        {transaction.status}
      </span>

      <div className="agent-attribution">
        {transaction.agent ? (
          <span>
            <Bot size={11} />
            AI
          </span>
        ) : (
          <span className="not-agent">—</span>
        )}
      </div>

      <button className="transaction-more">
        <MoreHorizontal size={16} />
      </button>
    </div>
  );
}

function WebhookEvent({
  type,
  order,
  time,
  success = false,
  failed = false,
}: {
  type: string;
  order: string;
  time: string;
  success?: boolean;
  failed?: boolean;
}) {
  return (
    <div className="webhook-event">
      <div
        className={
          failed
            ? "webhook-icon failed"
            : success
            ? "webhook-icon success"
            : "webhook-icon"
        }
      >
        {failed ? (
          <XCircle size={13} />
        ) : success ? (
          <Check size={13} />
        ) : (
          <CreditCard size={13} />
        )}
      </div>

      <div className="webhook-info">
        <strong>{type}</strong>
        <span>{order}</span>
      </div>

      <span className="webhook-time">{time}</span>
    </div>
  );
}

function RevenueSource({
  label,
  value,
  percent,
}: {
  label: string;
  value: string;
  percent: string;
}) {
  return (
    <div className="revenue-source">
      <div>
        <span>{label}</span>
        <strong>{value}</strong>
      </div>

      <div className="source-bar">
        <div style={{ width: percent }} />
      </div>

      <span className="source-percent">{percent}</span>
    </div>
  );
}

export default Transactions;